name: ez_qr
description: QR code (scan QRCode and picture) recognition （AndroidView/UiKitView）
version: 1.0.0
authors:
  ["Fogaiht<thiagofpf@gmail.com>", "MaxweelFreitas<maxweel.freitas@gmail>"]
homepage: https://github.com/fogaiht/ez_qr

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.4
  permission_handler: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.flutterando.ez_qr
    pluginClass: FlutterQrReaderPlugin
  assets:
    - assets/tool_img.png
    - assets/tool_qrcode.png
    - assets/tool_flashlight_close.png
    - assets/tool_flashlight_open.png
